import fetch from "node-fetch";


/**
 * Attempts to log a user in based on the google sign in
 * @param {json} userinfo - the json generated by the google sign in api with user's info
 */

const attemptLogin = async (userinfo) => {
    const data = {
        email: userinfo.user.email,
        first_name: userinfo.user.givenName,
        last_name: userinfo.user.familyName
    } 
    let reqHeader = new Headers();
    reqHeader.append("Authorization", "Bearer " + userinfo.idToken);
    reqHeader.append('Content-Type', 'application/json');
    
    let initObject = {
        method: 'POST', headers: reqHeader, body: JSON.stringify(data)
    };
    
    const url = "https://b03x6lkzlb.execute-api.us-east-1.amazonaws.com/dev";

    let resData = await fetch(url + "/login", initObject)
        .then(response => {
            let result = response.json();
            return result;
        })
        .then(async(promise) => {
            
            return promise;
        })
        .catch(function(err) {
            console.log("ERROR", err);
        });
    return resData;
}

/**
 * Attempts to log a user's report based on a clicked location into the obstructions database
 * 
 * @param {number} latitude - latitude of clicked location
 * @param {number} longitude - longitude of clicked location
 * @param {string} type - type of report
 * @param {string} description - description typed by user
 * @param {string} token - token of user's login
 * 
 */
const attemptReport = async (latitude, longitude, type, description, token) => {
    const data = {
        latitude: latitude,
        longitude: longitude,
        type: type,
        description: description
    } 
    let reqHeader = new fetch.Headers();
    reqHeader.append('Content-Type', 'application/json');
    reqHeader.append("Authorization", "Bearer " + token);
    
    let initObject = {
        method: 'POST', headers: reqHeader, body: JSON.stringify(data)
    };
    const url = "https://b03x6lkzlb.execute-api.us-east-1.amazonaws.com/dev";
    let resData = await fetch(url + "/report", initObject)
    .then(response => {
        let result = response.json();
        return result;
    })
    .then(async(promise) => {
        return promise;
    })
    .catch(function(err) {
        console.log("ERROR", err);
    });
    
    return resData;
}

/**
 * Calls mapbox's geocoding API to return addresses based ona  user's query 
 * @param {string} search - the query a user types into the maps search bar
 * @param {string} mapboxToken - the global mapbox token
 * 
 */
const geocodingAPI = async (search, mapboxToken, boundingBox) => {
    const address = encodeURIComponent(search.trim())

    const bb = "-180%2C-90%2C180%2C90" //example
    //const geoURL = "https://api.mapbox.com/geocoding/v5/mapbox.places/" + address + ".json?country=us&bbox="+ bb +"&language=en&access_token="+mapboxToken;
    const geoURL = "https://api.mapbox.com/geocoding/v5/mapbox.places/" + address + ".json?country=us&language=en&access_token="+mapboxToken;
    //console.log(geoURL)
    const response = await fetch(geoURL);
    
    let resData = await response.text()
    resData = JSON.parse(resData)
   
    return resData;
}

/**
 * Calls mapbox's geocoding API to return an address based on given longitude and latitude
 * @param {number} longitude - the longitude given
 * @param {number} latitude - the latitude given 
 * @param {string} mapboxToken - the global mapbox token
 * 
 */
const reverseGeocodingAPI = async(longitude, latitude, mapboxToken) => {
    const geoURL = "https://api.mapbox.com/geocoding/v5/mapbox.places/"+longitude+","+latitude+".json?country=us&limit=1&access_token="+mapboxToken;
    // console.log(geoURL)
    const response = await fetch(geoURL);
    
    let resData = await response.text()
    resData = JSON.parse(resData)
   
    return resData;
}

/**
 * Attempts to inject a saved location into the saved location table
 * @param {Array} coordinates - array of coordinates of clicked location
 * @param {string} token - token of user's login
 * @param {string} mapboxToken - the global mapbox token
 * 
 */
const saveLocation = async(coordinates, token, mapboxToken) => {
    const reverse = await reverseGeocodingAPI(coordinates[0], coordinates[1], mapboxToken)
    const features = reverse.features[0]
    const longitude = features.geometry.coordinates[0]
    const latitude = features.geometry.coordinates[1]
    
    const data = {
        longitude: longitude,
        latitude: latitude,
    };
    
    let reqHeader = new fetch.Headers();
    reqHeader.append('Content-Type', 'application/json');
    reqHeader.append("Authorization", "Bearer " + token);

    let initObject = {
        method: 'POST', headers: reqHeader, body: JSON.stringify(data)
    };

    const url = "https://b03x6lkzlb.execute-api.us-east-1.amazonaws.com/dev";
    let resData = await fetch(url + "/save-location", initObject)
        .then(response => {
            let result = response.json();
            return result;
        })
        .then(async(promise) => {
            return promise;
        })
        .catch(function(err) {
            console.log("ERROR", err);
        });
    
}

/**
 * Fetches any saved locations under the user's profile
 * @param {string} token - token of user's login
 */
const getSavedLocations = async(token) => {
    let reqHeader = new fetch.Headers();
    reqHeader.append('Content-Type', 'application/json');
    reqHeader.append("Authorization", "Bearer " + token);

    let initObject = {
        method: 'GET', headers: reqHeader
    };

    const url = "https://b03x6lkzlb.execute-api.us-east-1.amazonaws.com/dev";
    // const url = "http://localhost:5000"
    let response = await fetch(url + "/saved-locations", initObject)
    let resData = await response.text()
    resData = JSON.parse(resData)
    return resData
}


/**
 * Deletes any saved locations under the user's profile in the saved locations table
 * 
 * @param {number} long - longitude of location
 * @param {number} lat - latitude of location
 * @param {string} token - token of user's login
 */
const deleteSavedLocation = async(long, lat, token) => {
    const data = {
        longitude: long,
        latitude: lat,
    };


    let reqHeader = new Headers();
    reqHeader.append('Content-Type', 'application/json');
    reqHeader.append("Authorization", "Bearer " + token);

    let initObject = {
        method: 'POST', headers: reqHeader, body: JSON.stringify(data)
    };

    const url = "https://b03x6lkzlb.execute-api.us-east-1.amazonaws.com/dev";
    let resData = await fetch(url + "/remove-saved-location", initObject)
        .then(response => {
            let result = response.json();
            console.log("delete here");
            return result;
        })
        .then(async(promise) => {
            console.log("delete here2");
            return promise;
        })
        .catch(function(err) {
            console.log("ERROR", err);
        });   
}

/**
 * Deletes the user's account and accosiated information from pave's tables
 * 
 * @param {string} token - token of user's login
 */
const deleteAccount = async(token) => {
    console.log("deleting...")

    let reqHeader = new Headers();
    reqHeader.append('Content-Type', 'application/json');
    reqHeader.append("Authorization", "Bearer " + token);

    let initObject = {
        method: 'GET', headers: reqHeader
    };

    const url = "https://b03x6lkzlb.execute-api.us-east-1.amazonaws.com/dev";
    let response = await fetch(url + "/deactivate", initObject)

    let resData = await response.text()
    resData = JSON.parse(resData)

    console.log(resData);
    return resData
}



export {
    attemptLogin,  
    attemptReport, 
    geocodingAPI, 
    reverseGeocodingAPI, 
    saveLocation, 
    getSavedLocations, 
    deleteSavedLocation, 
    deleteAccount,
    };

